[project]
name = "backend"
version = "0.1.0"
description = "Maintenance Request Tracker REST API"
readme = "README.md"
authors = [
    { name = "Wade Little", email = "wade@palmettoadvisors.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "uvicorn[standard]>=0.54.0",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
